### ISSUE TITLE
Using skeleton template,joint location error

### ISSUE THREAD

**Issue by sarahxinxi** [mukailab/ssdr#2]
I am using skeleton template to compute bone transformation for each mesh example, but I find he bone transformations generated by [Le and Deng 2012] do not always rotate around thejoints. Therefore, I refer to the paper 'Robust and Accurate Skeletal Rigging from Mesh Sequences'. The problem is that i can not determine the joint location in my skeleton template Cjk which the paper uses

**Comment by TomohikoMukai** [comment]
Unfortunately I could not fully understand your point. What do you mean by 'skeleton template'? I also wonder it is a issue of my implementation? Probably you can find more sophisticated implementation at https://www.ea.com/seed/news/open-source-dem-bones .

**Comment by sarahxinxi** [comment]
skeleton template means a LBS model including skeletal structure, skinning weights, joint locations. I want to calculate bone transformation corresponding to all the mesh sequences with this skeleton template, but I find bone transformations generated by [Le and Deng 2012] do not always rotate around thejoints. The problem is solved in  the paper 'Robust and Accurate Skeletal Rigging from Mesh Sequences'. Howerver, I can not acheive the accurate resulting acoording to the paper.

I also ask you that you have decentrialized the two sets of vertices in the function SubtractCentroid() ,why you  calculate the centroid of the two sets of vertices again int the function CalcPointsAlignment()

**Comment by TomohikoMukai** [comment]
I think the problem you have might be pose estimation, motion retargeting, or inverse kinematics rather than skinning decomposition what SSDR and its variants solve. I have no clear idea of the best solution for your problem, unfortunately. Regarding the second question, please refer the Le and Deng's paper.
